-- Los textos de la portada pública dejan de estar escritos en el código del frontend y pasan a
-- editarse desde la cuenta de administradora. El motivo es que son de Arlette: cada cambio de
-- redacción tenía que pasar por un cambio de código, y así los edita ella directamente.
--
-- El contenido se siembra con los textos que ella entregó (ver docs/textos-arlette.md). Los
-- cuerpos son HTML porque se editan con el mismo editor de texto enriquecido que los documentos.

CREATE TABLE textos_landing (
    clave          VARCHAR(50) PRIMARY KEY,
    contenido      TEXT        NOT NULL,
    actualizado_en TIMESTAMP
);

INSERT INTO textos_landing (clave, contenido) VALUES
('HERO_TITULO', $txt$Pipoe$txt$),

('HERO_SUBTITULO', $txt$De cómo hacer Planificación Situacional aprendiendo$txt$),

('DESCRIPCION_TITULO', $txt$Descripción$txt$),

('DESCRIPCION_CUERPO', $txt$<p>El Modelo PipoE recoge y condensa más de cuatro décadas de estudio, docencia, investigación, asesoría y ejercicio profesional en planificación, evaluación y, más recientemente, política pública. Su construcción se ha nutrido de su aplicación en diferentes espacios de actuación —universidades, organismos internacionales, instituciones públicas, empresas privadas, cooperativas y organizaciones sociales de la más amplia diversidad— y en distintos ámbitos de toma de decisiones —directivo, gerencial, operativo, de base y núcleos primarios—.</p><p>Nace en respuesta a las visiones predominantes sobre la naturaleza y los propósitos de la planificación en el imaginario institucional, organizativo y social. Por regla general, las creencias más conocidas y difundidas acerca de la práctica de la planificación pueden ubicarse a lo largo de un continuum. En sus extremos se encuentran, de un lado, la planificación entendida como una especie de dictado de designios, producto de la voluntad; y, del otro, entendida únicamente como un inventario de actividades elaborado con antelación a la fecha prevista para su ejecución.</p>$txt$),

('MODELO_TITULO', $txt$De cómo hacer Planificación Situacional aprendiendo$txt$),

('MODELO_CUERPO', $txt$<p>La planificación es el método de trabajo que antecede y preside la acción, como diría mi maestro Carlos Matus. <strong>Situacional</strong> es la categoría central que orienta, organiza e imprime coherencia a su ejercicio y, en términos sencillos, se define por la presencia de actores y acciones. <strong>Aprendiendo</strong> alude a que la práctica se realiza mediante aproximaciones sucesivas: dialogando, indagando, consultando, buscando referentes, revisando y reformulando tantas veces como resulte necesario. Se trata de ir construyendo y aprendiendo en el proceso, no de pretender elaborar de una sola vez un producto acabado.</p><p>Desde esa perspectiva, el Modelo PipoE se sustenta en la articulación de cinco componentes esenciales —no etapas—: Promoción, indagación, programación, organización —incluidas la coordinación y la administración— y Evaluación. De las iniciales de estos componentes deriva la sigla PipoE.</p><p>Los usos del Modelo PipoE abarcan desde la planificación de una acción de la vida cotidiana o una actividad institucional u organizativa hasta una política pública, pasando por proyectos, programas y planes.</p><p>Queda abierta la invitación a apropiarse del Modelo PipoE y a disfrutar de la aventura <em>De cómo hacer Planificación Situacional aprendiendo</em>.</p>$txt$),

('BIOGRAFIA_TITULO', $txt$¿Quién es Arlette Pichardo Muñiz?$txt$),

('BIOGRAFIA_CUERPO', $txt$<p>Nació en Santo Domingo, República Dominicana, y la mayor parte de su trayectoria académica y profesional la ha desarrollado en y desde Costa Rica. Estudió Sociología, realizó una maestría en Planificación del Desarrollo y un doctorado en Educación, con especialidad en Mediación Pedagógica. Es académica jubilada de la Universidad Nacional (UNA) de Costa Rica, donde desempeñó distintas funciones de docencia, investigación, asesoría en planificación y evaluación y gestión académica.</p><p>Desde sus primeras publicaciones es considerada como un referente iberoamericano en materia de enfoques emergentes en planificación y evaluación, entre otras razones, porque su trabajo se dirige tanto a quienes se inician en estos temas como a quienes ya tienen experiencia de larga data. Sus obras de amplia circulación internacional, dentro y fuera de América Latina y el Caribe, integran catálogos de librerías internacionales y están disponibles en bibliotecas universitarias, centros de documentación especializados y repositorios institucionales. Se utilizan como libros de texto en programas docentes de grado y posgrado y como referentes en investigaciones teóricas y aplicaciones prácticas en diversas entidades, incluso en campos del saber más allá de las ciencias sociales.</p><p>A lo largo de su trayectoria ha liderado procesos de planificación, investigación y evaluación en más de 20 países y ha sido profesora visitante en más de media docena de universidades iberoamericanas. En ese recorrido, ha sido reconocida como una de las Mujeres Pioneras de la Universidad Nacional (UNA) de Costa Rica, por ser la primera mujer en asumir la dirección general del Centro Internacional de Política Económica para el Desarrollo Sostenible (CINPE-UNA). Ha recibido diversas distinciones, entre ellas: Conferenciante principal de la Sociedad Puertorriqueña de Evaluación (SPE), de la Conferencia conjunta ReLAC-REDLACME-IDEAS y de la Semana gLOCAL de Evaluación e invitada a dictar la Conferencia magistral de apertura de la Maestría en Planificación de la UNA y la Conferencia de inauguración del 50 aniversario de la Facultad de Ciencias Sociales de la misma universidad. Además, ha sido distinguida como miembra ad honorem de la Red de Evaluación y Seguimiento de Costa Rica (RedEvalCR) y reconocida por sus méritos académicos por la Facultad de Ciencias Económicas y Sociales de la Universidad Autónoma de Santo Domingo (UASD) de la República Dominicana.</p><p>En la actualidad, combina la reflexión y la escritura independiente con el liderazgo de un proyecto de responsabilidad social en su país natal. Desde esos espacios crece la ilusión de estar-en-proceso-de-aprender al articular el talento humano en los entornos institucionales y sociales en los que se desenvuelve y al aportar a creaciones innovadoras, como la App del Modelo PipoE.</p>$txt$);
